server:
  port: 8080 # Cổng mặc định của Backend

ecommerce:
  app:
    jwtSecret: NGVwYjN6YzhxMnB4OXU1aWp2bThkaWZrNnBoMmduOHltdmwycTM4ajYxazA # ${JWT_SECRET}
    jwtExpirationMs: 86400000

cloudinary:
  cloud-name: v1wlw369 # ${CLOUDINARY_CLOUD_NAME}
  api-key: 121559934927727 # ${CLOUDINARY_API_KEY}
  api-secret: uRRxbAPacR482odVkq63vBl5jCc # ${CLOUDINARY_API_SECRET}

spring:
  datasource:
    # Đường link kết nối trực tiếp đến máy chủ Supabase
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?user=postgres.lxzgocsjecrvkcubkmmd&password=Haibara1808%23
    username: postgres.lxzgocsjecrvkcubkmmd
    password: Haibara1808%23
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5    # Chỉ cho phép tối đa 5 kết nối đồng thời (Nhỏ hơn giới hạn 15 của Supabase)
      minimum-idle: 1         # Chỉ giữ 1 kết nối chạy ngầm khi không có ai dùng
      idle-timeout: 300000    # Đóng kết nối nếu không dùng sau 5 phút (300,000 ms)
      connection-timeout: 20000 # Thời gian chờ tối đa để lấy kết nối là 20s
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Ép Hibernate chuyển sang nói ngôn ngữ PostgreSQL
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true



  # Cấu hình giới hạn dung lượng file upload 
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB